# for sending email
EMAIL_HOST = 
EMAIL_APP_PASSWORD = 

# for spreadsheet
folder_id = 
sheet_name = 
spreadsheet_name = 

[gcp_service_account]
type = 
project_id = 
private_key_id = 
private_key = 
client_email = 
client_id = 
auth_uri = 
token_uri = 
auth_provider_x509_cert_url = 
client_x509_cert_url = 
