name: Deploy with Docker on Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Export secrets from SECRETS
        run: |
          echo "${{ secrets.SECRETS }}" > .env
          set -a
          source .env
          set +a

      - name: Create .streamlit/secrets.toml
        run: |
          mkdir -p .streamlit
          echo "EMAIL_HOST = '${EMAIL_HOST}'" >> .streamlit/secrets.toml
          echo "EMAIL_APP_PASSWORD = '${EMAIL_APP_PASSWORD}}'" >> .streamlit/secrets.toml
          echo "folder_id = '${FOLDER_ID}'" >> .streamlit/secrets.toml
          echo "sheet_name = '${SHEET_NAME}'" >> .streamlit/secrets.toml
          echo "spreadsheet_name = '${SPREADSHEET_NAME}'" >> .streamlit/secrets.toml
          echo "[gcp_service_account]" >> .streamlit/secrets.toml
          echo "type = '${GCP_TYPE}'" >> .streamlit/secrets.toml
          echo "project_id = '${GCP_PROJECT_ID}'" >> .streamlit/secrets.toml
          echo "private_key_id = '${GCP_PRIVATE_KEY_ID}'" >> .streamlit/secrets.toml
          echo "private_key = '${GCP_PRIVATE_KEY}'" >> .streamlit/secrets.toml
          echo "client_email = '${GCP_CLIENT_EMAIL}'" >> .streamlit/secrets.toml
          echo "client_id = '${GCP_CLIENT_ID}'" >> .streamlit/secrets.toml
          echo "auth_uri = '${GCP_AUTH_URI}'" >> .streamlit/secrets.toml
          echo "token_uri = '${GCP_TOKEN_URI}'" >> .streamlit/secrets.toml
          echo "auth_provider_x509_cert_url = '${GCP_AUTH_PROVIDER_CERT_URL}'" >> .streamlit/secrets.toml
          echo "client_x509_cert_url = '${GCP_CLIENT_CERT_URL}'" >> .streamlit/secrets.toml
          >> .streamlit/secrets.toml
          echo "universe_domain = '${GCP_UNIVERSE_DOMAIN}'" >> .streamlit/secrets.toml

      - name: Set up Google Cloud SDK
        # uses: google-github-actions/setup-gcloud@v2
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${GCP_SA_PROJECT_ID}
          service_account_key: ${GCP_SA_KEY}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          gcloud builds submit --tag gcr.io/${GCP_SA_PROJECT_ID}/diagnostico-app --project ${GCP_SA_PROJECT_ID}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy diagnostico-app \
            --image gcr.io/${GCP_SA_PROJECT_ID}/diagnostico-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8501
